version: "3.9"
services: 
    nginx_proxy:
        image: nginx:1.20-alpine
        container_name: nginx_proxy
        restart: always
        depends_on: 
            - jenkins
            - nexus
            - sonarqube
        links:
            - nexus
            - jenkins
            - sonarqube
        volumes: 
            - $PWD/files:/etc/nginx/conf.d:ro
        ports: 
            - 80:80
    jenkins:
        image: jenkins/jenkins:2.305
        container_name: jenkins
        environment:
            JENKINS_OPTS: --prefix=/jenkins
        volumes: 
            - jenkins-data:/var/jenkins_home
            - /var/run/.docker.sock:/var/run/docker.sock
    nexus:
        image: sonatype/nexus3:3.33.0
        container_name: nexus
        environment: 
            NEXUS_CONTEXT: nexus
        volumes:
            - nexus-data:/nexus-data
    sonarqube:
        image: sonarqube:8.9.2-community
        container_name: sonarqube
        depends_on:
            - sonarqube-db
        environment:
            SONAR_WEB_CONTEXT: /sonarqube
            SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
        volumes:
            - sonarqube-data:/opt/sonarqube/data
            - sonarqube-extensions:/opt/sonarqube/extensions
    sonarqube-db:
        image: postgres:12
        container_name: sonarqube-db
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
        - postgresql:/var/lib/postgresql
        - postgresql-data:/var/lib/postgresql/data


volumes: 
    jenkins-data:
    nexus-data:
    sonarqube-data:
    sonarqube-extensions:
    postgresql:
    postgresql-data:   
    
